export const TEST_IDS = {
  // Main components
  BESTSELLERS: "BESTSELLERS",

  // Ticket components
  PRODUCT_CARD: "PRODUCT_CARD",
  ADD_TO_CART_BUTTON: "ADD_TO_CART_BUTTON",

  // Modal
  ADD_TO_CART_MODAL: "ADD_TO_CART_MODAL",
  DATEPICKER: "DATEPICKER",
  QUANTITY_INPUT: "QUANTITY_INPUT",
  ADD_TO_CART_MODAL_BUTTON: "ADD_TO_CART_MODAL_BUTTON",

  // Cart
  GO_TO_CART_BUTTON: "GO_TO_CART_BUTTON",
  CART_ITEMS: "CART_ITEMS",
  CHECKOUT_BUTTON: "CHECKOUT_BUTTON",
  TOTAL_PRICE_VALUE: "TOTAL_PRICE_VALUE",

} as const;

export type TestId = keyof typeof TEST_IDS